gauss_jordan

In [24]:
import numpy as np

In [31]:
import numpy as np
def gauss_jordan(a, b):
    a = a.astype(float)
    b = b.astype(float)

    if a.shape[0] != a.shape[1]:
        raise ValueError("Matrix A must be square.")
    if a.shape[0] != b.size:
        raise ValueError("Length of b must equal number of rows of A.")

    n = b.size
    aug = np.hstack([a, b.reshape(-1, 1)])

    for i in range(n):
        if abs(aug[i, i]) < 1e-12:
            swap_row = np.argmax(abs(aug[i:, i])) + i
            if abs(aug[swap_row, i]) < 1e-12:
                raise ValueError("Singular matrix; no unique solution.")
            aug[[i, swap_row]] = aug[[swap_row, i]]

        aug[i] /= aug[i, i]        

        for j in range(n):
            if i != j:
                aug[j] -= aug[j, i] * aug[i]

    return aug[:, -1]

In [33]:
A = np.array([[0.02,  5.52,   2.07,   0.93],
              [8.45,  8.45,   5.44,   7.06],
              [77.89, 32.56, 40.67,  43.45],
              [9.22, 40.81, -143.45, 17.34]])

B = np.array([10, 20, 15, 25])

print(gauss_jordan(A, B))

[-3.9081579   0.54501987  0.51099248  6.46440754]


In [35]:
aug = np.hstack([A, B.reshape(-1, 1)])
aug



array([[ 2.0000e-02,  5.5200e+00,  2.0700e+00,  9.3000e-01,  1.0000e+01],
       [ 8.4500e+00,  8.4500e+00,  5.4400e+00,  7.0600e+00,  2.0000e+01],
       [ 7.7890e+01,  3.2560e+01,  4.0670e+01,  4.3450e+01,  1.5000e+01],
       [ 9.2200e+00,  4.0810e+01, -1.4345e+02,  1.7340e+01,  2.5000e+01]])

## gauss elimination method 

In [ ]:
import numpy as np

def gauss_elimination(a, b):
    n = len(b)
    aug = np.hstack((a.astype(float), b.reshape(-1, 1).astype(float)))

    for i in range(n):
        for j in range(i+1,n):
            if i != j:
                factor = aug[j][i] / aug[i][i]
                aug[j] = aug[j] - factor * aug[i]
    
    x = np.zeros(n)
    for i in range(n):
        x[i] = aug[i][-1] / aug[i][i]
    return x



A = np.array([
    [0.02, 5.52, 2.02],
    [8.05, 9.52, 5.96],
    [7.89, 3.56, 2.04]
])

B = np.array([0.98, 20.64, 10.35])

solution = gauss_elimination(A, B)
print("Solution:")
for i, val in enumerate(solution):
    print(f"x{i+1} = {val:.4f}")

In [45]:
import numpy as np

def gauss_jordan(a, b):
    n = len(b)
    aug = np.hstack((a.astype(float), b.reshape(-1, 1).astype(float)))

    for i in range(n):
        
        for j in range(i+1,n):
            if i != j:
                factor = aug[j][i] / aug[i][i]
                aug[j] = aug[j] - factor * aug[i]

    
    x = np.zeros(n)
    for i in range(n):
        x[i] = aug[i][-1] / aug[i][i]

    return x



A = np.array([
    [0.02, 5.52, 2.02],
    [8.05, 9.52, 5.96],
    [7.89, 3.56, 2.04]
])

B = np.array([0.98, 20.64, 10.35])

solution = gauss_jordan(A, B)
print("Solution:")
for i, val in enumerate(solution):
    print(f"x{i+1} = {val:.4f}")

Solution:
x1 = 49.0000
x2 = 0.1690
x3 = 5.2497


In [43]:
A = np.array([
    [0.02, 5.52, 2.02],
    [8.05, 9.52, 5.96],
    [7.89, 3.56, 2.04]
])

B = np.array([0.98, 20.64, 10.35])

n = len(B)
aug = np.hstack((A.astype(float), B.reshape(-1, 1).astype(float)))

for i in range(n):
        
        for j in range(i+1,n):
            if i != j:
                factor = aug[j][i] / aug[i][i]
                aug[j] = aug[j] - factor * aug[i]


In [44]:
aug

array([[ 2.00000000e-02,  5.52000000e+00,  2.02000000e+00,
         9.80000000e-01],
       [ 0.00000000e+00, -2.21228000e+03, -8.07090000e+02,
        -3.73810000e+02],
       [-8.88178420e-16,  0.00000000e+00, -1.69622778e+00,
        -8.90467210e+00]])

In [ ]:
aug